# Generated by Django 5.0.3 on 2024-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_department_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(default=None, max_length=3, verbose_name='doctor.Department'),
        ),
    ]
