# Generated by Django 5.0.3 on 2024-05-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_department_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ManyToManyField(blank=True, default=None, related_name='doctors', to='doctor.department'),
        ),
    ]
